import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOW = "2026-05-09T12:57:00.000Z"


def technique(tid, name, global_name, tactics, description, channels, targets, prerequisites, observables, detection, mitigation, evidence, mapping):
    details = [
        description,
        "",
        f"**Nome global:** {global_name}",
        f"**Canais usados:** {channels}",
        f"**Alvos comuns:** {targets}",
        f"**Pré-requisitos:** {prerequisites}",
        "",
        "**Sinais observáveis:**",
        *[f"- {item}" for item in observables],
        "",
        "**Detecção:**",
        *[f"- {item}" for item in detection],
        "",
        "**Mitigação:**",
        *[f"- {item}" for item in mitigation],
        "",
        f"**Evidências úteis:** {evidence}",
        f"**Relações com F3/MITRE ATT&CK:** {mapping}",
    ]
    return {
        "id": tid,
        "name": name,
        "description": "\n".join(details),
        "tactics": tactics,
        "subtechniques": [],
        "isAttack": False,
        "version": "0.1",
        "lastModified": NOW,
    }


tactics = [
    {"id": "BRFA0001", "name": "Preparação", "description": "Ações para criar, obter ou organizar recursos usados em golpes financeiros no Brasil, como contas laranja, chips, perfis falsos, anúncios, documentos, chaves PIX, QR Codes, maquininhas e infraestrutura de comunicação.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
    {"id": "BRFA0002", "name": "Aproximação", "description": "Ações para iniciar contato, atrair ou posicionar a vítima em um canal controlado pelo fraudador, incluindo anúncios falsos, mensagens em redes sociais, ligações, grupos, marketplaces e contatos por WhatsApp.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
    {"id": "BRFA0003", "name": "Engenharia Social", "description": "Ações para manipular confiança, urgência, medo, autoridade, ganância ou vínculo emocional da vítima, explorando linguagem, cultura, canais e hábitos brasileiros.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
    {"id": "BRFA0004", "name": "Comprometimento de Conta/Dispositivo", "description": "Ações para obter controle ou influência sobre contas, identidades digitais, dispositivos, linhas telefônicas, apps bancários, mensageria ou sessões autenticadas.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
    {"id": "BRFA0005", "name": "Manipulação de Pagamento", "description": "Ações para alterar, induzir, falsificar ou redirecionar instruções de pagamento, incluindo PIX, boleto, cartão, link de pagamento, QR Code, carteira digital e maquininhas.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
    {"id": "BRFA0006", "name": "Execução Financeira", "description": "Ações que efetivamente resultam em transferência, compra, saque, contratação, liberação de produto, concessão de crédito, contestação abusiva ou outro impacto financeiro.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
    {"id": "BRFA0007", "name": "Cash-out/Lavagem", "description": "Ações para converter, distribuir, ocultar ou lavar valores obtidos, usando contas laranja, bets, cripto/P2P, boletos, adquirentes, subadquirentes, saques ou compras de bens facilmente revendáveis.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
    {"id": "BRFA0008", "name": "Evasão/Encobrimento", "description": "Ações para dificultar detecção, rastreio, bloqueio, recuperação de valores, atribuição ou investigação, incluindo troca de contas, documentos falsos, pressão para retirada de anúncio/conversa e fragmentação de valores.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
    {"id": "BRFA0009", "name": "Revitimização", "description": "Ações para explorar novamente a mesma vítima ou seus contatos após o primeiro golpe, incluindo recuperação falsa de valores, novas cobranças, chantagem, uso de listas de contatos e venda de dados.", "isAttack": False, "version": "0.1", "lastModified": NOW, "tactic": True},
]


techniques = [
    technique("BRF-0001", "Falso Comprovante de PIX", "Fake Instant Payment Confirmation", ["BRFA0005", "BRFA0006"], "O fraudador apresenta comprovante falso, editado ou reutilizado para convencer a vítima a liberar produto, serviço, reserva ou reembolso antes da confirmação real do crédito.", "WhatsApp, marketplace, delivery, venda presencial, Instagram", "lojistas, autônomos, vendedores P2P", "vítima aceita screenshot como prova", ["pressão por liberação imediata", "comprovante visual sem crédito liquidado", "E2E/ID transacional inexistente ou reutilizado"], ["conciliar extrato antes da entrega", "validar ID transacional e instituição", "detectar imagens reutilizadas"], ["liberar somente após crédito confirmado", "treinar operação para ignorar screenshot", "automatizar conciliação"], "screenshot, extrato, ID/E2E PIX, conversa, horário", "F3: Fake Payment Confirmation; Transfer of Funds"),
    technique("BRF-0002", "QR Code PIX Adulterado", "Payment QR Code Substitution", ["BRFA0005"], "Substituição ou adulteração de QR Code estático/dinâmico para redirecionar o pagamento PIX a uma conta controlada pelo fraudador.", "impresso, WhatsApp, e-mail, site, balcão, eventos", "comércios, condomínios, eventos, doadores", "vítima confere apenas valor ou nome parcial", ["beneficiário divergente", "QR Code colado sobre original", "domínio ou arquivo alterado"], ["comparar recebedor esperado", "inventariar QR Codes publicados", "monitorar alterações em páginas de pagamento"], ["usar QR dinâmico autenticado", "exibir recebedor esperado", "proteger materiais físicos"], "imagem do QR, payload EMV, recebedor, logs de alteração", "F3: Payment QR Code Substitution"),
    technique("BRF-0003", "Chave PIX Manipulada", "Instant Payment Key Manipulation", ["BRFA0005"], "O fraudador induz a vítima a usar uma chave PIX incorreta ou parecida, explorando pressa, falso atendimento ou troca de mensagens.", "WhatsApp, SMS, e-mail, marketplace", "consumidores, pagadores recorrentes, empresas", "pagador não valida titularidade", ["chave recém-informada", "titular incompatível", "troca repentina de chave"], ["validar titular antes da confirmação", "alertar troca de beneficiário recorrente"], ["cadastro prévio de favorecidos", "dupla checagem por canal confiável"], "chave, titular, mensagens, comprovantes", "F3: Instant Payment Key Manipulation"),
    technique("BRF-0004", "Falso Boleto", "Bank Slip Manipulation", ["BRFA0005", "BRFA0006"], "Criação, alteração ou substituição de boleto para que o pagamento seja direcionado a beneficiário fraudulento.", "e-mail, buscadores, WhatsApp, portal falso", "consumidores, empresas, condomínios", "vítima paga boleto sem conferir beneficiário", ["linha digitável divergente", "beneficiário diferente", "desconto/urgência incomum"], ["validar beneficiário e banco emissor", "monitorar páginas falsas indexadas"], ["emitir por canais autenticados", "educar para conferir beneficiário"], "PDF, linha digitável, beneficiário, origem do arquivo", "F3: Bank Slip Manipulation"),
    technique("BRF-0005", "Falsa Central Bancária", "Impersonated Financial Institution Support", ["BRFA0002", "BRFA0003", "BRFA0005"], "Contato falso em nome de banco, cooperativa, fintech ou bandeira para induzir transações, instalação de app, fornecimento de códigos ou entrega de cartão.", "telefone, WhatsApp, SMS", "correntistas, idosos, alta renda", "vítima acredita em autoridade bancária", ["número spoofado", "pedido de transação teste", "orientação para não desligar"], ["detectar chamadas seguidas de transações incomuns", "correlacionar alteração cadastral e pagamento"], ["campanhas anti-transação-teste", "callbacks oficiais no app", "bloqueio contextual"], "gravação, número, logs app, transações", "F3: Social Engineering; Authorized Push Payment Manipulation"),
    technique("BRF-0006", "Falso Motoboy", "Card Collection Courier Scam", ["BRFA0003", "BRFA0006"], "Fraudador convence a vítima a entregar cartão físico, chip ou documentos a um suposto portador/motoboy enviado pelo banco.", "telefone, WhatsApp, visita presencial", "correntistas, idosos", "vítima acredita que cartão será recolhido/cancelado", ["coleta física após chamada", "cartão cortado preservando chip", "saques/compra próximos à coleta"], ["correlacionar chamada e uso presencial", "alertar compras após bloqueio declarado"], ["comunicar que banco não recolhe cartão", "bloquear cartão via app/agência"], "CFTV, endereço, cartão, chamadas, transações", "F3: Social Engineering; Card Fraud"),
    technique("BRF-0007", "WhatsApp Clonado ou Tomado", "Messaging Account Takeover", ["BRFA0004", "BRFA0009"], "Tomada de conta de WhatsApp para pedir dinheiro a contatos, capturar grupos ou revitimizar rede de relacionamento.", "WhatsApp, SMS, ligação", "usuários finais, pequenos negócios", "código de verificação ou sessão comprometida", ["pedidos urgentes a contatos", "novo dispositivo vinculado", "mudança de foto/nome"], ["alertar contatos por anomalia de mensagem", "monitorar denúncias em massa"], ["ativar verificação em duas etapas", "não compartilhar códigos"], "logs do WhatsApp, conversas, chaves PIX usadas", "F3: Account Takeover; Compromise Accounts"),
    technique("BRF-0008", "Golpe do Parente no WhatsApp", "Family Impersonation Payment Scam", ["BRFA0002", "BRFA0003", "BRFA0006"], "Fraudador se passa por filho, parente ou amigo com número novo e solicita PIX urgente.", "WhatsApp, SMS", "familiares, idosos", "vítima não confirma por ligação ou canal alternativo", ["número novo", "história de celular quebrado", "urgência emocional"], ["detectar favorecidos novos e narrativa de urgência", "limites adaptativos"], ["verificação por chamada", "atraso para primeiro PIX a favorecido novo"], "conversa, número, chave PIX, titular", "F3: Authorized Push Payment Manipulation"),
    technique("BRF-0009", "Falso Investimento", "Investment Scam", ["BRFA0002", "BRFA0003", "BRFA0006", "BRFA0007"], "Oferta fraudulenta de investimento com promessa de retorno alto, muitas vezes usando influenciadores falsos, grupos e plataformas simuladas.", "Instagram, Telegram, WhatsApp, sites", "varejo, aposentados, investidores iniciantes", "vítima acredita na rentabilidade ou prova social", ["rentabilidade garantida", "saques iniciais simulados", "depósitos para múltiplas contas"], ["monitorar contas recebedoras relacionadas", "identificar domínios e anúncios"], ["alertas de promessa de retorno", "bloqueio de anúncios fraudulentos"], "anúncio, domínio, conversas, transações", "F3: Fraudulent Investment; Fake Website"),
    technique("BRF-0010", "Golpe da Tarefa/Remuneração", "Task Job Scam", ["BRFA0002", "BRFA0003", "BRFA0006", "BRFA0009"], "Promessa de renda por tarefas simples que evolui para depósitos, taxas ou aportes para liberar ganhos fictícios.", "WhatsApp, Telegram, Instagram", "desempregados, jovens, trabalhadores informais", "vítima busca renda extra", ["pagamentos pequenos iniciais", "níveis VIP", "taxas para sacar"], ["mapear grupos e contas recebedoras", "detectar múltiplos depósitos crescentes"], ["educar sobre taxa para receber", "fricção em pagamentos para contas suspeitas"], "prints de tarefas, grupo, depósitos, plataforma", "F3: Advance Fee Fraud; Social Engineering"),
    technique("BRF-0011", "Falso Leilão", "Fake Auction", ["BRFA0002", "BRFA0005", "BRFA0006"], "Site ou anúncio falso de leilão usa logotipos e linguagem jurídica para induzir pagamento de caução, lance ou taxa.", "Google Ads, Instagram, sites, WhatsApp", "compradores de veículos e imóveis", "vítima acredita em leiloeiro/órgão legítimo", ["domínio recente", "pressão por caução", "beneficiário pessoa física"], ["monitorar domínios similares", "validar leiloeiro em junta comercial"], ["consulta em fontes oficiais", "não pagar fora da plataforma"], "URL, anúncio, boleto/PIX, CNPJ/CPF", "F3: Fake Website; Payment Manipulation"),
    technique("BRF-0012", "Marketplace com Intermediador Falso", "Marketplace Intermediary Impersonation", ["BRFA0002", "BRFA0003", "BRFA0005"], "Fraudador se passa por comprador, vendedor ou plataforma e manipula fluxo de pagamento/entrega fora do ambiente oficial.", "OLX, Mercado Livre, WhatsApp", "compradores e vendedores P2P", "negociação migra para canal externo", ["pedido para sair da plataforma", "e-mail falso de confirmação", "frete/intermediador incomum"], ["detectar links/e-mails falsos", "denúncias por telefone/chave PIX"], ["manter pagamento e chat na plataforma", "alertas contra intermediadores"], "anúncio, chat, e-mail, comprovante", "F3: Fake Payment Confirmation; Social Engineering"),
    technique("BRF-0013", "Conta Laranja Alugada", "Mule Account Recruitment", ["BRFA0001", "BRFA0007", "BRFA0008"], "Recrutamento, aluguel ou compra de contas bancárias/fintech para receber e movimentar valores de golpes.", "redes sociais, Telegram, comunidades locais", "jovens, vulneráveis, MEIs", "pessoa aceita ceder conta por comissão", ["múltiplos créditos seguidos de saídas", "dispositivo/localidade incomum", "conta recém-aberta"], ["modelos de mule account", "correlação entre vítimas e cash-out"], ["KYC reforçado", "limites progressivos", "educação sobre crime"], "KYC, device, transações, conversas de recrutamento", "F3: Mule Account Recruitment; Transfer of Funds"),
    technique("BRF-0014", "Cash-out via Bet", "Betting Platform Cash-out", ["BRFA0007", "BRFA0008"], "Valores de origem fraudulenta são depositados em plataformas de apostas para circular, fracionar, justificar ou sacar por outros meios.", "bets, PIX, contas laranja", "instituições financeiras, PSPs, bets", "conta em bet aceita depósitos/saques rápidos", ["depósito e saque sem padrão de jogo", "múltiplas origens para mesma conta", "fracionamento"], ["monitorar deposit/withdraw velocity", "compartilhar sinais com PSP/bet"], ["KYC e AML em bets", "retenção por risco"], "transações PIX, conta bet, histórico de apostas", "F3: Monetization; Conversion of Funds"),
    technique("BRF-0015", "Cash-out via Cripto/P2P", "Cryptocurrency P2P Cash-out", ["BRFA0007", "BRFA0008"], "Conversão de valores de golpes em criptoativos por exchanges, P2P, OTC informal ou intermediários.", "PIX, exchanges, Telegram, P2P", "vítimas, bancos, exchanges", "conta recebedora acessa liquidez cripto", ["PIX para brokers P2P", "saques rápidos", "múltiplas carteiras"], ["correlacionar contas com exchanges/P2P", "identificar padrões de layering"], ["KYC/AML robusto", "bloqueio cooperativo rápido"], "hashes, contas, conversas P2P, extratos", "F3: Convert to Cryptocurrency"),
    technique("BRF-0016", "Fraude com Maquininha", "POS/Acquirer Abuse", ["BRFA0001", "BRFA0006", "BRFA0007"], "Uso indevido de POS, adquirentes ou subadquirentes para passar cartões, simular vendas, antecipar recebíveis ou movimentar valores.", "maquininhas, links de pagamento, TEF", "adquirentes, lojistas, consumidores", "credenciamento ou POS disponível", ["MCC incompatível", "ticket médio anômalo", "chargebacks concentrados"], ["monitorar onboarding e TPV", "analisar chargeback/antecipação"], ["KYC de estabelecimento", "limites por maturidade"], "cadastro merchant, transações, chargebacks, geolocalização", "F3: Fraudulent Merchant Account"),
    technique("BRF-0017", "Golpe em Delivery/Comércio Local", "Local Commerce Delivery Scam", ["BRFA0002", "BRFA0005", "BRFA0006"], "Fraudes em pedidos locais com falso pagamento, retirada por terceiros, comprovante falso ou chargeback após entrega.", "WhatsApp, iFood-like, Instagram, balcão", "restaurantes, pequenos comércios", "operação libera pedido sem conciliação", ["comprovante antes do crédito", "retirada por moto sem validação", "endereço inconsistente"], ["conciliar pedidos e recebimentos", "validar entregador/código"], ["retirada com código", "pagamento integrado", "política anti-screenshot"], "pedido, conversa, comprovante, CFTV, entrega", "F3: Fake Payment Confirmation"),
    technique("BRF-0018", "Falso Sequestro", "Virtual Kidnapping Extortion", ["BRFA0003", "BRFA0006"], "Ameaça falsa e pressão emocional para obter transferência imediata sob alegação de sequestro ou risco a familiar.", "telefone, WhatsApp", "famílias, idosos", "vítima não consegue confirmar segurança do familiar", ["ameaça em chamada contínua", "pedido de PIX rápido", "impedimento de desligar"], ["identificar múltiplos pagamentos sob coerção", "palavras-chave em atendimento"], ["orientar desligar e confirmar", "limites e alertas para idosos"], "número, gravação, PIX, relato", "F3: Extortion; Social Engineering"),
    technique("BRF-0019", "Golpe do Consignado/INSS/FGTS", "Payroll/Benefit Loan Scam", ["BRFA0002", "BRFA0003", "BRFA0006"], "Fraudador usa promessa de revisão, liberação, portabilidade ou saque de benefício para obter dados, taxas ou contratar crédito indevido.", "telefone, WhatsApp, SMS, correspondentes", "aposentados, pensionistas, trabalhadores", "dados pessoais e benefício expostos", ["contato ativo sobre benefício", "taxa antecipada", "contrato não reconhecido"], ["monitorar originação anômala", "validar biometria/prova de vida"], ["confirmação por canal oficial", "bloqueio de consignado não solicitado"], "contrato, gravação, IP/device, benefício", "F3: Identity Fraud; Loan Fraud"),
    technique("BRF-0020", "Contestação/MED Abusivo", "Instant Payment Refund Abuse", ["BRFA0006", "BRFA0008"], "Uso abusivo de contestação, MED ou chargeback após recebimento de produto/serviço ou em conluio para reaver valores indevidamente.", "PIX, cartões, atendimento", "lojistas, PSPs, consumidores", "mecanismo de disputa disponível", ["contestação logo após entrega", "histórico repetitivo", "evidências inconsistentes"], ["analisar padrão do reclamante", "conciliar entrega e comunicação"], ["coleta robusta de evidência", "política de disputa baseada em risco"], "protocolo MED, entrega, conversa, logs", "F3: Refund Abuse; Chargeback Fraud"),
    technique("BRF-0021", "Link de Pagamento Falso", "Fake Payment Link", ["BRFA0005", "BRFA0006"], "Envio de link falso que simula checkout, banco, carteira ou adquirente para capturar pagamento, cartão ou credenciais.", "SMS, WhatsApp, e-mail, redes sociais", "consumidores e lojistas", "vítima clica fora do domínio oficial", ["URL encurtada ou parecida", "checkout sem HTTPS confiável", "MCC/beneficiário estranho"], ["detecção de typosquatting", "análise de links reportados"], ["domínios oficiais claros", "bloqueio de links maliciosos"], "URL, HTML, pagamento, logs DNS", "F3: Fake Website; Phishing"),
    technique("BRF-0022", "Instalação de Acesso Remoto", "Remote Access Tool Social Engineering", ["BRFA0003", "BRFA0004", "BRFA0006"], "Vítima é induzida a instalar app de acesso remoto ou compartilhamento de tela para que o fraudador opere app bancário ou colete códigos.", "telefone, WhatsApp, lojas de app", "correntistas, empresas", "vítima segue orientação de falso suporte", ["app remoto instalado", "sessão durante transação", "permissões de acessibilidade"], ["detectar apps de risco no device", "anomalia de toque/navegação"], ["bloquear operação com screen sharing", "alertas no app"], "logs do dispositivo, app instalado, sessão bancária", "F3/ATT&CK: Remote Access Software; Abuse Accessibility Features"),
    technique("BRF-0023", "Troca de Chip/SIM Swap", "SIM Swap", ["BRFA0004", "BRFA0008"], "Transferência fraudulenta da linha telefônica da vítima para interceptar OTPs, recuperar contas e autorizar transações.", "operadora, lojas, atendimento", "correntistas e usuários de carteiras", "dados cadastrais suficientes", ["perda súbita de sinal", "troca de SIM antes de login", "OTP via SMS usado"], ["integrar sinal de SIM swap", "bloquear operações pós-troca"], ["MFA não dependente de SMS", "cooldown após troca de chip"], "registro operadora, horários, OTPs, transações", "F3: MFA Interception; Account Takeover"),
    technique("BRF-0024", "Uso de Documentos Falsos no Onboarding", "Synthetic/Forged Identity Onboarding", ["BRFA0001", "BRFA0008"], "Criação de contas usando documentos falsos, adulterados, sintéticos ou de terceiros para receber valores e dificultar atribuição.", "apps bancários, fintechs, adquirentes", "PSPs, bancos, wallets", "onboarding remoto vulnerável", ["selfie/documento inconsistente", "device repetido", "endereço compartilhado"], ["biometria e prova de vida", "grafo de dispositivos/dados"], ["KYC em camadas", "revisão manual por risco"], "documentos, biometria, device, IP, cadastro", "F3: Create Fake Materials; Identity Fraud"),
    technique("BRF-0025", "Anúncio Falso em Rede Social", "Social Media Malvertising Scam", ["BRFA0001", "BRFA0002"], "Anúncios pagos ou perfis falsos promovem produtos, investimentos, leilões, vagas ou benefícios inexistentes.", "Instagram, Facebook, TikTok, Google Ads", "consumidores, investidores, desempregados", "plataforma permite impulsionamento/alcance", ["preço muito abaixo", "perfil recém-criado", "comentários bloqueados"], ["monitorar ads e landing pages", "correlacionar denúncias"], ["remoção rápida", "verificação de anunciantes"], "criativo, conta anunciante, URL, pagamentos", "F3/ATT&CK: Malvertising; Fake Website"),
    technique("BRF-0026", "Phishing de Gov.br/Banco", "Brazilian Portal Credential Phishing", ["BRFA0002", "BRFA0004"], "Páginas e mensagens falsas simulam Gov.br, bancos, Receita, Detran ou benefícios para capturar credenciais e dados.", "SMS, e-mail, WhatsApp, anúncios", "cidadãos, MEIs, beneficiários", "vítima acredita no órgão/instituição", ["domínio parecido", "pedido de senha/código", "tema de multa/restituição"], ["detectar kits e domínios", "monitorar credenciais comprometidas"], ["MFA resistente a phishing", "takedown e educação"], "URL, kit, credenciais, logs", "F3/ATT&CK: Phishing; Credential Harvesting"),
    technique("BRF-0027", "Falsa Recuperação de Valores", "Recovery Scam", ["BRFA0009", "BRFA0003", "BRFA0006"], "Após golpe anterior, fraudador promete recuperar dinheiro mediante taxa, procuração, novo PIX ou dados adicionais.", "WhatsApp, telefone, e-mail", "vítimas recentes", "dados da vítima circulam em listas", ["contato menciona golpe anterior", "taxa para recuperar", "falso advogado/policial"], ["correlacionar vítimas com novos pagamentos", "monitorar narrativas de recuperação"], ["alertar vítimas no atendimento", "nunca cobrar taxa de recuperação"], "contato, taxa, dados usados, transações", "F3: Re-victimization; Advance Fee Fraud"),
    technique("BRF-0028", "Fragmentação de Valores", "Transaction Structuring", ["BRFA0007", "BRFA0008"], "Valores são divididos em múltiplas transações, contas, horários ou instituições para evitar limites, alertas e bloqueios.", "PIX, TED, cartões, wallets", "bancos, PSPs, laranjas", "várias contas/canais disponíveis", ["muitos PIX abaixo de limite", "fan-out/fan-in", "sequência em curto período"], ["análise de grafo e velocity", "detectar fan-out para laranjas"], ["limites dinâmicos", "bloqueio por rede"], "extratos, contas relacionadas, horários", "F3: Defense Evasion; Transfer of Funds"),
    technique("BRF-0029", "Lavagem via Compra e Revenda", "Resale of Goods", ["BRFA0007"], "Compra de bens líquidos ou revendáveis com valores fraudados para converter dinheiro em mercadoria e posterior revenda.", "e-commerce, lojas físicas, gift cards, eletrônicos", "varejo, marketplaces, vítimas", "aceitação de pagamento fraudulento", ["compra de alto valor", "retirada rápida", "múltiplos cartões/contas"], ["monitorar compra-retirada", "anomalia de endereço/device"], ["KYC para alto valor", "retenção antifraude"], "pedido, entrega, device, pagamento", "F3: Monetization; Conversion to Goods"),
    technique("BRF-0030", "Coleta e Reuso de Listas de Contatos", "Contact List Harvesting for Re-victimization", ["BRFA0004", "BRFA0009"], "Após comprometer conta/dispositivo, fraudador coleta contatos para novos golpes, pedidos de PIX ou campanhas segmentadas.", "WhatsApp, e-mail, redes sociais", "usuários e seus contatos", "conta/dispositivo comprometido", ["mensagens em massa", "pedidos similares a vários contatos", "exportação de contatos"], ["detectar envio anômalo", "denúncias por rede de contatos"], ["proteção de sessão", "notificação de login novo", "2FA"], "lista de contatos, mensagens, sessão, device", "F3: Compromise Accounts; Re-victimization"),
]

matrix = tactics + techniques

(ROOT / "src" / "data" / "matrix-data.json").write_text(json.dumps(matrix, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
(ROOT / "public" / "br-fraud-v1.json").write_text(json.dumps(matrix, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
(ROOT / "public" / "br-fraud-stix.json").write_text(json.dumps({"type": "bundle", "id": "bundle--br-fraud-framework-v0.1", "spec_version": "2.1", "objects": []}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
(ROOT / "public" / "br-fraud-navigator.json").write_text(json.dumps({"name": "Matriz Brasileira de Fraudes Financeiras v0.1", "versions": {"layer": "4.5", "navigator": "4.9"}, "domain": "br-fraud", "description": "Camada inicial da Matriz Brasileira de Fraudes Financeiras."}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print(f"Wrote {len(tactics)} tactics and {len(techniques)} techniques.")